apiVersion: v1
kind: Service
metadata:
  name: map-api-test
  labels:
    app: qu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      
  type: LoadBalancer
  selector:
    app: web